Feature/ml 1472
TomsZvirbuliss/m2 pull request #14
Opened 2023-03-02 12:38 UTC by TomsZvirbuliss

2023-03-02 12:44 UTC, laurisdedumets requested changes
Tu esi pārliecināts, ka šīs izmaiņas strādās pareizi?

Redzu, ka tu izmainīji gan Composer failus, gan uzinstalēji modeli iekš app/code. Domāju, ka tev, vai nu palaižot `composer install`, vai `bin/magento s:up`, izmetīs kļūdu, ka modulis jau deklarēts.

2023-03-02 13:06 UTC, TomsZvirbuliss commented
Uz development vides uzpushojas veiksmīgi, bija problēmas tikkai ar magento atslēgām bet citādi viss strādā.

2023-03-03 12:09 UTC, laurisdedumets commented on package.json.sample
>    "name": "magento2",
Praktiski šī nav problēma, it īpaši, jo tas ir tikai `.sample` fails, bet cenšamies necommitot neko, kas nav vajadzīgs konkrēto izmaiņu ieviešanai

2023-03-03 12:09 UTC, laurisdedumets approved these changes

2023-03-03 12:10 UTC, merged